config/routes.rb
Rails.application.routes.draw do
  
  resources :medical_records
  resources :pets
  
  get 'welcome/index'
  
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :pets

  accepts_nested_attributes_for :pets
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  
  # Associations
  belongs_to :kind, inverse_of: :pets
  has_many :medical_records

  accepts_nested_attributes_for :medical_records, reject_if: :all_blank, allow_destroy: true

  # Validations
  validates :name, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :get_pets, only: [:show]

  def index
    @pets = Pet.all.page(params[:page]).per(10)
  end
  
  def new
    @pet = Pet.new
    @kind_options = Kind.all
  end
  
  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet), notice: 'Pet successfuly created!'
    else
      render :new
    end
  end

  def show
  end

  def edit
    @kind_options = Kind.all
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet.id), notice: 'Pet successfuly updated!'
    else
      render :edit
    end
  end
  
  def destroy
    if @pet.destroy
      redirect_to pet_path, notice: 'Pet successfuly deleted!'
    else
      render :index
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:id, :name, :birthdate, :breed, :kind_id,
    medical_records_attributes:[:id, :patient_symptoms, :applied_treatment, :done, :_destroy])
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def get_pets
    @pets = Pet.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @pets = Pet.all.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  
  def translate_method(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Error_Message"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PetBooking!</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'application'%>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Petbooking!</span></a>
            </div>
            <div class="clearfix"></div>
            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li>
                  <li><%= link_to welcome_index_path do %>
                    <i class="fa fa-home"></i>Pets
                  <% end %>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav class="nav navbar-nav">
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <%= yield %>
            </div>
          </div>
        </div>
        <!-- /page content -->
        <!-- footer content -->
        <footer>
          <div class="pull-right">
            PetBooking - Bootstrap by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <%= javascript_include_tag 'application'%>
  
  </body>
</html>

app/views/medical_records/edit.html.erb
<% if @pet.errors.any? %>
  <% @pet.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
  <% end %>
<% end %>

<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Prontuário Registering:<small>Novo Prontuário</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_with(url: welcome_path, model: @pet, local: true) do |form| %>
        <div class="item form-group">
            <%= form.label :name, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
            <%= form.text_field :name, class:"form-control" %>
            </div>
          </div>
            <%= form.fields_for :medical_records do |medical_records| %>
              <div class="item form-group">
                <%= medical_records.label :patient_symptoms, class:"col-form-label col-md-3 col-sm-3 label-align" %>
                <div class="col-md-6 col-sm-6 ">
                <%= medical_records.text_field :patient_symptoms, class:"form-control" %>
                </div>
              </div>
              
              <div class="item form-group">
                <%= medical_records.label :applied_treatment, class:"col-form-label col-md-3 col-sm-3 label-align" %>
                <div class="col-md-6 col-sm-6 ">
                  <%= medical_records.text_field :applied_treatment, class:"form-control" %>
                </div>
              </div>
            <% end %>
          <div class="ln_solid"></div>
          <div class="item form-group">
            <div class="col-md-6 col-sm-6 offset-md-3">
              <td><%= link_to t('links.Cancel'), "#" %></td>
              <button class="btn btn-primary" type="reset">Reset</button>
              <button type="submit" class="btn btn-success">Submit</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/medical_records/index.html.erb
  <% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="clearfix"></div>
  <div class="col-md-12 col-sm-12  ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Listing Prontuários<small>Todos os prontuários</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><%= link_to 'Novo Prontuário', "#" %></li>
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= @mrecords.human_attribute_name("id") %></th>
              <th><%= @mrecords.human_attribute_name("patient_symptoms") %></th>
              <th><%= @mrecords.human_attribute_name("applied_treatment") %></th>
              <th>Nome do Pet</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @mrecords.each do |m_record| %>
              <tr>
                <td><%= m_record.id %></td>
                <th><%= m_record.patient_symptoms %></th>
                <td><%= m_record.applied_treatment %></td>
                <td><%= m_record.pet.name %></td>
                <td><%#= link_to "Show", pet_path(@pet) %></td>
                <td><%#= link_to "Edit", edit_pet_path(@pet) %></td>
                <td><%#= link_to "Delete", pet, method: :delete, data: {confirm: 'Are you sure?'} %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @mrecords %>
      </div>
    </div>
  </div>

app/views/medical_records/new.html.erb
<% if @mrecord.errors.any? %>
  <% @mrecord.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
  <% end %>
<% end %>

<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <h2><%= @mrecord.model_name.human(count: 2) %> Registering:<small>Novo <%= @mrecord.model_name.human %></small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for @mrecord do |f| %>
        <div class="item form-group">
            <%= f.label :pet_id, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
            <%= f.text_field :pet_id class:"form-control" %>
            </div>
          </div>
          <div class="item form-group">
            <%= f.label :patient_symptoms, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
            <%= f.text_field :patient_symptoms, class:"form-control" %>
            </div>
          </div>
          
          <div class="item form-group">
            <%= f.label :applied_treatment, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%= f.text_field :applied_treatment, class:"form-control" %>
            </div>
          </div>
          
          <div class="ln_solid"></div>
          <div class="item form-group">
            <div class="col-md-6 col-sm-6 offset-md-3">
              <button class="btn btn-primary" type="button">Cancel</button>
              <button type="submit" class="btn btn-success"><% t('links.Submit') %></button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/_medical_record_fields.html.erb
  <div class="nested-fields">
     <div class="item form-group">
      <%= link_to_remove_association('Remover Prontuário', f, class:"btn btn-outline-primary btn-sm") %>
    </div>
    <div class="item form-group">
      <%= f.label :patient_symptoms, class:"col-form-label col-md-3 col-sm-3 label-align" %>
      <div class="col-md-6 col-sm-6 ">
        <%= f.text_field :patient_symptoms, class:"form-control" %>
      </div>
    </div>
    <div class="item form-group">
      <%= f.label :applied_treatment, class:"col-form-label col-md-3 col-sm-3 label-align" %>
      <div class="col-md-6 col-sm-6 ">
        <%= f.text_field :applied_treatment, class:"form-control" %>
      </div>
    </div>
  </div> 

app/views/pets/edit.html.erb
<%= render partial: 'pets/shared/form',
locals: { action_message: t('headers.editing', model: @pet.model_name.human) } %>

app/views/pets/new.html.erb
<%= render partial: 'pets/shared/form',
locals: { action_message: t('headers.registering', model: @pet.model_name.human) } %>

app/views/pets/shared/_form.html.erb
<% if @pet.errors.any? %>
  <% @pet.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
  <% end %>
<% end %>

<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <h2><%= "#{action_message}" %> <%= @pet.model_name.human %></h1></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_with(model: @pet, local: true) do |form| %>
          <div class="item form-group">
            <%= form.label :kind_id, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%= form.collection_select(:kind_id, @kind_options, :id, :description, 
              {}, {class:"form-control"} )%>
            </div>
          </div>

          <div class="item form-group">
            <%= form.label :name, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
            <%= form.text_field :name, class:"form-control" %>
            </div>
          </div>
          
          <div class="item form-group">
            <%= form.label :birthdate, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%= form.date_field :birthdate, class:"form-control" %>
            </div>
          </div>

          <div class="item form-group">
            <%= form.label :breed, class:"col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%= form.text_field :breed, class:"form-control" %>
            </div>
          </div>
          
          <div id="medical_records">
            <%= form.fields_for :medical_records do |medical_record| %>
              <%= render partial: "medical_record_fields", locals: { f: medical_record } %>
            <% end %>
            <div class="col-md-6 col-sm-6 offset-md-3">
              <%= link_to_add_association 'Add Prontuário', form, :medical_records,
               class:"btn btn-outline-success btn-sm" %>
            </div><br />
          </div>
          <div class="ln_solid"></div>
          <div class="item form-group">
            <div class="col-md-6 col-sm-6 offset-md-3">
              <td><%= link_to t('links.Cancel'), welcome_index_path, class:"btn btn-primary" %></td>
              <%= form.submit t('links.Submit'), class:"btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

      <div class="clearfix"></div>
        <div class="col-md-12 col-sm-12  ">
          <div class="x_panel">
            <div class="x_title">
              <h2><%= @pet.model_name.human %>: <%= @pet.name %></h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><%= link_to t('links.Home'), welcome_index_path %></li>
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th><%= translate_method(@pets, :id) %></th>
                    <th><%= translate_method(@pets, :name) %></th>
                    <th>Tipo</th>
                    <th><%= translate_method(@pets, :birthdate) %></th>
                    <th><%= translate_method(@pets, :breed) %></th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= @pet.id %></td>
                    <th><%= @pet.name %></th>
                    <td><%= @pet.kind.description %></td>
                    <td><%= l @pet.birthdate %></td>
                    <td><%= @pet.breed %></td>
                    <td><%= link_to t('links.Edit'), edit_pet_path(@pet) %></td>
                    <td><%= link_to t('links.Delete'), pet_path(@pet), method: :delete, data: {confirm: 'Are you sure?'} %></td>
                  </tr>
                </tbody>
              </table>

              <div class="col-md-12 col-sm-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><%= @pet.name %><small><%= @pet.medical_records.model_name.human(count: 2) %></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><%= link_to t('links.Manage', model: @pet.medical_records.model_name.human(count: 2)), edit_pet_path(@pet) %></li>
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th><%= translate_method(@pets, :id) %></th>
                    <th><%= translate_method(@pet.medical_records, :patient_symptoms) %></th>
                    <th><%= translate_method(@pet.medical_records, :applied_treatment) %></th>
                    <th>Data do Prontuário</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @pet.medical_records.each do |mrec|%>
                    <tr>
                      <td><%= mrec.id %></td>
                      <th><%= mrec.patient_symptoms %></th>
                      <td><%= mrec.applied_treatment %></td>
                      <td><%= l @pet.birthdate %></td>
                      <td><%= link_to t('links.Edit'), edit_pet_path(@pet) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="clearfix"></div>
  <div class="col-md-12 col-sm-12  ">
    <div class="x_panel">
      <div class="x_title">
        <h2><%= t('headers.registered', model: @pets.model_name.human(count: 2)) %></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><%= link_to t('links.New', model: @pets.model_name.human), new_pet_path %></li>
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= @pets.human_attribute_name("id") %></th>
              <th>Tipo</th>
              <th><%= @pets.human_attribute_name("name") %></th>
              <th><%= @pets.human_attribute_name("birthdate") %></th>
              <th><%= @pets.human_attribute_name("breed") %></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @pets.each do |pet| %>
              <tr>
                <td><%= pet.id %></td>
                <th><%= pet.kind.description %></th>
                <td><%= pet.name %></td>
                <td><%= l pet.birthdate %></td>
                <td><%= pet.breed %></td>
                <td><%= link_to t('links.Show'), pet_path(pet) %></td>
                <td><%= link_to t('links.Edit'), edit_pet_path(pet) %></td>
                <td><%= link_to t('links.Delete'), pet_path(pet), method: :delete, data: {confirm: 'Are you sure?'} %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
          <%= paginate @pets %>
      </div>
    </div>
  </div>